#   _____          _                                                     ______  __  __          _
#  / ____|        | |                    /\                             |  ____|/ _|/ _|        | |
# | |    _   _ ___| |_ ___  _ __ ___    /  \   _ __ _ __ ___   ___  _ __| |__  | |_| |_ ___  ___| |_
# | |   | | | / __| __/ _ \| '_ ` _ \  / /\ \ | '__| '_ ` _ \ / _ \| '__|  __| |  _|  _/ _ \/ __| __|
# | |___| |_| \__ \ || (_) | | | | | |/ ____ \| |  | | | | | | (_) | |  | |____| | | ||  __/ (__| |_
#  \_____\__,_|___/\__\___/|_| |_| |_/_/  _ \_\_|  |_| |_| |_|\___/|_|  |______|_| |_| \___|\___|\__|
# |  _ \        |__   __| |              | |       | |     |__ \
# | |_) |_   _     | |  | |__   ___  ___ | |__   __| | __ _   ) |
# |  _ <| | | |    | |  | '_ \ / _ \/ _ \| '_ \ / _` |/ _` | / /
# | |_) | |_| |    | |  | | | |  __/ (_) | | | | (_| | (_| |/ /_
# |____/ \__, |    |_|  |_| |_|\___|\___/|_| |_|\__,_|\__, |____|
#         __/ |                                        __/ |
#        |___/                                        |___/

# You can configure the effects on any armour. To do so, you just have to do like this:
# armor_name:
#   id:
#   effect:
#   visible:

# visible = true/false
# To configure the effect, do: effect_name:level

# Setup here all armor you want
armor:
    golden_helmet:
      id: 314
      effect: "night_vision:1"
      visible: false
    golden_chestplate:
      id: 315
      effect: "health_boost:3"
      visible: false
    golden_leggings:
      id: 316
      effect: "speed:2"
      visible: false
    golden_boots:
      id: 317
      effect: "haste:2"
      visible: false
